apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: aya452/api-app:latest
          env:
            - name: QUOTES_API
              value: http://quotes:5000
          ports:
            - containerPort: 3000
