version: '2'
services:
  quotes:
    build:
      context: ./QuoteService
      dockerfile: app.dockerfile
    ports:
     - "5000:5000"
  api:
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    environment:
      - "QUOTE_API=quotes"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
    