apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091 # Le port d'accès depuis les nœuds
  type: NodePort
