apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          image: aya452/quotes-app:latest
          ports:
            - containerPort: 5000
          command: ["python", "main.py"]
